### ISSUE TITLE
Won't create more than 1 QR code

### ISSUE THREAD

**Issue by roccamorice** [JasonVonKrueger/MMM-QR-Remote-Link#2]
I tried to use this module to create 2 QR codes (one for remote control and the other for mealplan.  It does create the 2 QR codes but both QR codes are identical.  That is, they are labeled differently but both point to the last URL in the config file (which in my case is mealplan).  Therefore they both redirect to mealplan URL.

Note, the remote control URL is  address:9090/remote.html, the mealplan url is address:9090/mealplan

The config is shown below

 {
    module: 'MMM-QR-Remote-Link',
    position: 'top_bar',
    pages: {0:"top_bar",4: "top_bar"},
    config: {
        size: 75, // in pixels...height and width are set to this
        text: 'MagicMirror Remote',
        endpoint: '/remote.html' // must start with a "/"
    }
},
      {
    module: 'MMM-QR-Remote-Link',
    position: 'bottom_right',
    pages: {0:"bottom_right",4: "bottom_right"},
    config: {
        size: 75, // in pixels...height and width are set to this
        text: 'Weekly Menu Planner',
        endpoint: '/mealplan' // must start with a "/"
    }

*****NOTIFICATION*****  Also when I scan your QR codes in your readme file, they both give me the same URL

**Comment by JasonVonKrueger** [comment]
Hmmm .  Let me take a look and I’ll get back to you.

Thanks

**Comment by JasonVonKrueger** [comment]
@roccamorice --

I don't know how that slipped by QA.  I should fire myself.  Anyway, this is now fixed. Either git pull or grab the two updated .js files from https://github.com/JasonVonKrueger/MMM-QR-Remote-Link.  Please let me know whether that fixed it for you or not.  I'll close this in a few days.

**Comment by roccamorice** [comment]
Works great....thanks
